import { ThemeProvider } from "@mui/material";

import Footer from "@/layout/footer";
import Header from "@/layout/header";
import theme from "@/theme";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body>
          <header>
            <Header />
          </header>
          <main style={{ minHeight: "100vh" }}>{children}</main>
          <footer>
            <Footer />
          </footer>
        </body>
      </ThemeProvider>
    </html>
  );
}
