import { Poppins } from "next/font/google";
import { ThemeProvider } from "@mui/material";

import "./globals.css";
import theme from "@/theme";
import Header from "@/layout/header";
import Footer from "@/layout/footer";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body className={poppins.className}>
          <header>
            <Header />
          </header>
          <main>{children}</main>
          <footer>
            <Footer />
          </footer>
        </body>
      </ThemeProvider>
    </html>
  );
}
