export const services = [
  {
    iconSrc: "/images/S.png",
    title: "Social Media",
    link: "/social-media-marketing",
    subtitle: "Marketing",
    iconWidth: 87,
    maxWidth: "242px",
    mainImageSrc: "/images/home/service-1.webp",
  },
  {
    iconSrc: "/images/W.png",
    title: "Website",
    link: "/web-development",
    subtitle: "Development",
    iconWidth: 150,
    maxWidth: "240px",
    mainImageSrc: "/images/home/service-2.webp",
  },
  {
    iconSrc: "/images/S.png",
    title: "Search Engine",
    link: "/search-engine-optimization",
    subtitle: "Optimization",
    iconWidth: 87,
    maxWidth: "228px",
    mainImageSrc: "/images/home/service-3.webp",
  },
  {
    iconSrc: "/images/U.png",
    title: "UI/UX",
    link: "/ui-ux-design",
    subtitle: "Design",
    iconWidth: 90,
    maxWidth: "252px",
    mainImageSrc: "/images/home/service-4.webp",
  },
  {
    iconSrc: "/images/G.png",
    title: "Graphic",
    link: "/ui-ux-design",
    subtitle: "Design",
    iconWidth: 116,
    maxWidth: "214px",
    mainImageSrc: "/images/home/service-5.webp",
  },
  {
    iconSrc: "/images/G.png",
    title: "Google",
    link: "/graphics-designing",
    subtitle: "Ads",
    iconWidth: 116,
    maxWidth: "270px",
    mainImageSrc: "/images/home/service-6.webp",
  },
];
